namespace: production

replicaCount: 3

image:
  repository:  147467063105.dkr.ecr.us-east-1.amazonaws.com/color-app
  pullPolicy: IfNotPresent
  tag: "v2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::147467063105:role/color-app-eso-role
  name: "color-app"

podAnnotations: {}
podLabels: {}

lbService:
  port: 80
  targetPort: 8080
  annotations:
    type: "external"
    targetType: "ip"
    scheme: "internet-facing"


resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

configmap:
  APP_COLOR: "green"
  APP_ENV: "production"
  APP_MESSAGE: "Hello from Color-App Production! Deployed with Helm and External Secrets Operator"


volume:
  accessMode: ReadWriteOnce
  storageClass: gp2
  size: 1Gi

externalSecret:
  region: us-east-1
  serviceAccountName: color-app-sa
  refreshInterval: 1m
  remoteKey: color-app/prod
  keys:
  - name: SECRET_KEY
  - name: DB_PASSWORD
  - name: API_KEY

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
